pr:
  branches:
    include:
    - main
trigger: none


pool:
  vmImage: 'ubuntu-latest'

variables:
- group: core-api-production

stages:
- stage: 'Test'
  jobs:
   # - template: AzurePipelineHelpers/pipelines/templates/jobs/set-build-id.yml@template

    - job: 'Build'
      steps:
      - task: Bash@3
        inputs:
          targetType: 'inline'
          script: |
            echo $Password
            echo $(ApiUsers.SupplierFiiT.Password)
            echo $(ApiUsers.TggApi.Password)
            echo $(DATABASE_SERVER_PASSWORD)
            echo $(AzureAppConfiguration.ConnectionString)
        env:
            Password: $(ApiUsers.SupplierFiiT.Password)
       